import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {PhotoProvider} from "@/context/StyleContext";
import NextTopLoader from "nextjs-toploader";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Photobooth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PhotoProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url(/background.jpg)] bg-no-repeat bg-cover min-h-screen flex items-center justify-center flex-col`}
        >
          <NextTopLoader
            color="#e77f1e"
            zIndex={100000}
          />
          {children}
          <footer className="w-full fixed bottom-0">
            <p className=" flex items-center justify-center min-w-screen bg-black text-orange-500 text-center text-md p-2 gap-3">
              Ứng dụng này được phát triển và tài trợ bởi CLB VECTR
              <Image
                width={25}
                height={25}
                src="/vectr.png"
                alt="Vectr logo"
              />
            </p>
          </footer>
        </body>
      </html>
    </PhotoProvider>
  );
}
